name: conda-env
channels:
    - conda-forge
dependencies:
    - python=3.7.7
    - pip<=21.2.2
    - pip:
        - mlflow
        - cloudpickle==2.0.0
        - psutil==5.8.0
        - scikit-learn==1.0.2
